### ISSUE TITLE
色の統一

### ISSUE THREAD

**Issue by tamemoto** [tamemoto/Profill#132]
コーディング規約をはじめに作るべきだった
名刺コンポーネントの実装はtailwindだけじゃ厳しい

**Comment by manak1** [comment]
どうせなら綺麗にレスポンシブに対応したいので、名刺系はsassで書いても良いかもしれないですね！

**Comment by tamemoto** [comment]
そうですね！名刺と色は初めからsassの方がいいかもしれませんね笑
